version: '3'

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: dev
      POSTGRES_DB: wsp_math_class_exam
    healthcheck:
      test: ["CMD", "psql", "$POSTGRES_DB", "$POSTGRES_USER", "--version"]
      interval: 1m30s
      timeout: 10s
      retries: 3
  web:
    build: .
    environment:
      PYTHONUNBUFFERED: 1
    volumes:
      - ./app:/app
    ports:
      - "8000:8000"
    depends_on:
      - db